name: firstsite
favicon: null
layout_spectrum: 1
typography_spectrum: 0.506
title: "Acadiana School of the Arts is Lafayette, LA's premier school for music lessons."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#913494'
    - '#fff200'
    - '#0b94ca'
    - '#ffffff'
    - '#85c365'
  brandStrength: 0.5
  lightness: 0.9130329261533916
  saturation: 0.875
  rhythmicContrast: 0.3313966812565923
purpose: []
