name: firstsite
favicon: null
layout_spectrum: 0.866320998640731
typography_spectrum: 0.5078342959750444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#913494'
    - '#fff200'
    - '#0b94ca'
    - '#ffffff'
    - '#85c365'
  brandStrength: 0.6875
  lightness: 0.9130329261533916
  saturation: 0.9458651007153094
  rhythmicContrast: 0.3313966812565923
purpose: []
