typography_spectrum: 0.506
color:
  brandColors:
    - '#913494'
    - '#fff200'
    - '#0b94ca'
    - '#ffffff'
    - '#85c365'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: ASArts
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: >-
  Acadiana School of the Arts is Lafayette, LA's premier school for music
  lessons.
purpose: []
